apiVersion: v1
kind: Service
metadata:
  name: bizinv-db 
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31306 # exposed port we can communicate to
  selector:
    app: bizinv-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizinv-db
spec:
  selector:
    matchLabels:
      app: bizinv-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bizinv-db
    spec:
      containers:
        - image: mysql/mysql-server:latest
          name: bizinv-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: testing
          ports:
            - containerPort: 3306
              name: bizinv-db
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-backupscript
              mountPath: /var/script
            - name: mysql-backuplocation
              mountPath: /var/backup
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /data/app/db
        - name: mysql-backupscript
          hostPath:
            path: /data/app/cornjobs
        - name: mysql-backuplocation
          hostPath:
            path: /data/app/backup