apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizinv-frontendserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizinv-frontendserver
  template:
    metadata:
      labels:
        app: bizinv-frontendserver
    spec:
      containers:
        - name: bizinv-frontendserver
          image: l0ny1ucif32/bizinv-app
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bizinv-frontendserver
spec:
  selector:
    app: bizinv-frontendserver
  type: NodePort
  ports:
    - port: 3000 # expose the service on internal port 3000
      targetPort: 3000 # our NodeJS app listens on port 3000
